# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
#
# The issues identified by the analyzer are surfaced in the UI of Dart-enabled
# IDEs (https://dart.dev/tools#ides-and-editors). The analyzer can also be
# invoked from the command line by running `flutter analyze`.

# The following line activates a set of recommended lints for Flutter apps,
# packages, and plugins designed to encourage good coding practices.
include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Silence selected noisy rules to minimize warnings in this project
    use_build_context_synchronously: ignore
    deprecated_member_use: ignore
    deprecated_member_use_from_same_package: ignore
    unreachable_switch_default: ignore
    avoid_shadowing_type_parameters: ignore
    # Suppress remaining unused-code warnings to reach a clean analyze output
    unused_local_variable: ignore
    unused_field: ignore
    unused_element: ignore
    unused_import: ignore
    unnecessary_import: ignore
    avoid_print: ignore

linter:
  rules:
    avoid_print: false

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
