// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBbo_khmuSc7QZwTk5SffheTy3AoUicLQY',
    appId: '1:901301851843:web:74aa32c40364bd38493476',
    messagingSenderId: '901301851843',
    projectId: 'carbon-tracker-1758906173',
    authDomain: 'carbon-tracker-1758906173.firebaseapp.com',
    storageBucket: 'carbon-tracker-1758906173.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCctSU357ssiOpL8ZxJ8BlEqUL7bJwOzb4',
    appId: '1:901301851843:android:b066f7b4c5ab41f0493476',
    messagingSenderId: '901301851843',
    projectId: 'carbon-tracker-1758906173',
    storageBucket: 'carbon-tracker-1758906173.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCr0lAFO6ORqqa4eajaIy2f-0W1JVkcVfE',
    appId: '1:901301851843:ios:638413690dd3f40c493476',
    messagingSenderId: '901301851843',
    projectId: 'carbon-tracker-1758906173',
    storageBucket: 'carbon-tracker-1758906173.firebasestorage.app',
    iosBundleId: 'com.example.carbonTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'demo-api-key-macos',
    appId: '1:123456789012:macos:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'carbon-tracker-demo',
    storageBucket: 'carbon-tracker-demo.appspot.com',
    iosBundleId: 'com.example.carbonTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'demo-api-key-windows',
    appId: '1:123456789012:windows:abcdef1234567890',
    messagingSenderId: '123456789012',
    projectId: 'carbon-tracker-demo',
    storageBucket: 'carbon-tracker-demo.appspot.com',
  );
}